# Generated by Django 4.0.6 on 2022-07-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ModificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platan.devicetype')),
            ],
        ),
        migrations.CreateModel(
            name='GenerateSerialNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platan.devicetype')),
                ('modification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platan.modificationtype')),
            ],
        ),
    ]
