# Generated by Django 4.0.6 on 2022-07-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0002_rename_device_type_modificationtype_device_type1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modificationtype',
            old_name='device_type1',
            new_name='device_type',
        ),
        migrations.DeleteModel(
            name='GenerateSerialNumbers',
        ),
    ]
