# Generated by Django 4.0.6 on 2022-07-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0004_generateserialnumbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicetype',
            old_name='name',
            new_name='device_type',
        ),
        migrations.RenameField(
            model_name='modificationtype',
            old_name='name',
            new_name='modification_type',
        ),
    ]
