# Generated by Django 4.0.6 on 2022-07-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0005_rename_name_devicetype_device_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicetype',
            old_name='device_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='modificationtype',
            old_name='modification_type',
            new_name='name',
        ),
    ]
