# Generated by Django 4.0.6 on 2022-07-31 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0006_rename_device_type_devicetype_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenerateSerialNumbers',
        ),
    ]
