# Generated by Django 4.0.6 on 2022-07-31 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0007_delete_generateserialnumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateSerialNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platan.devicetype')),
                ('modification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platan.modificationtype')),
            ],
        ),
    ]
