# Generated by Django 4.0.6 on 2022-07-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0010_alter_modificationtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificationtype',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
