# Generated by Django 4.0.6 on 2022-07-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0012_detailtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtype',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
