# Generated by Django 4.0.6 on 2022-07-31 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0013_alter_detailtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateserialnumbers',
            name='detail_type',
            field=models.ForeignKey(default='789', on_delete=django.db.models.deletion.CASCADE, to='platan.detailtype'),
        ),
        migrations.AlterField(
            model_name='generateserialnumbers',
            name='device_type',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='platan.devicetype'),
        ),
        migrations.AlterField(
            model_name='generateserialnumbers',
            name='modification_type',
            field=models.ForeignKey(default='456', on_delete=django.db.models.deletion.CASCADE, to='platan.modificationtype'),
        ),
    ]
