# Generated by Django 4.0.6 on 2022-07-31 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0015_alter_generateserialnumbers_detail_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateserialnumbers',
            name='detail_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platan.detailtype'),
        ),
        migrations.AlterField(
            model_name='generateserialnumbers',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platan.devicetype'),
        ),
        migrations.AlterField(
            model_name='generateserialnumbers',
            name='modification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platan.modificationtype'),
        ),
    ]
