# Generated by Django 4.0.6 on 2022-07-31 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0016_alter_generateserialnumbers_detail_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOfProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='generateserialnumbers',
            name='place_of_production',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='platan.placeofproduction'),
        ),
    ]
