# Generated by Django 4.0.6 on 2022-07-31 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0017_placeofproduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateserialnumbers',
            name='place_of_production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platan.placeofproduction'),
        ),
    ]
