# Generated by Django 4.0.6 on 2022-08-01 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0021_alter_generateserialnumbers_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailtype',
            options={'verbose_name': 'Тип изделия', 'verbose_name_plural': 'Тип изделия'},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'verbose_name': 'Тип устройства', 'verbose_name_plural': 'Тип устройства'},
        ),
        migrations.AlterModelOptions(
            name='modificationtype',
            options={'verbose_name': 'Тип модификации', 'verbose_name_plural': 'Тип модификации'},
        ),
        migrations.AlterModelOptions(
            name='placeofproduction',
            options={'verbose_name': 'Место производства', 'verbose_name_plural': 'Место производства'},
        ),
        migrations.AlterField(
            model_name='generateserialnumbers',
            name='device_type',
            field=models.ForeignKey(default='--', on_delete=django.db.models.deletion.CASCADE, to='platan.devicetype'),
        ),
    ]
