# Generated by Django 4.0.6 on 2022-08-01 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0022_alter_detailtype_options_alter_devicetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateserialnumbers',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generateserialnumbers',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platan.devicetype'),
        ),
    ]
