# Generated by Django 4.0.6 on 2022-08-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0023_alter_generateserialnumbers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateserialnumbers',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
