# Generated by Django 4.1 on 2022-09-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0024_alter_generateserialnumbers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateserialnumbers',
            name='count',
            field=models.IntegerField(default=1, max_length=4),
        ),
    ]
