# Generated by Django 4.1 on 2022-09-09 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platan', '0025_alter_generateserialnumbers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateserialnumbers',
            name='count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
